/*
 * CBoot - C Project Bootstrapping Tool v2.0
 * Documentation generator (新规范 v2.0)
 *
 * 生成四种文档:
 *  - README.md: 模块注释 + 文档链接 + 目录结构
 *  - API.md: API函数/宏/结构体/类型及注释
 *  - DEV.md: 函数业务逻辑 + 所有子域注释 + 调用栈
 *  - DOC.md: 所有注释 + 可跳转目录 + 定义
 */

#include "cboot.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* ------------------------------------------------------------------ */
/* Forward declarations                                               */
/* ------------------------------------------------------------------ */

static void generate_mod_readme(Domain *mod, const char *dir);
static void generate_mod_api(Domain *mod, const char *dir);
static void generate_mod_dev(Domain *mod, const char *dir);
static void generate_mod_doc(Domain *mod, const char *dir);
static void generate_project_readme(Project *proj, const char *output_dir);

/* ------------------------------------------------------------------ */
/* Helpers                                                             */
/* ------------------------------------------------------------------ */

static int is_api(Domain *d) {
    if (!d) return 0;
    switch (d->type) {
        case DOMAIN_FUNCTION:
            return ((FunctionDomain *)d)->mode == API_MODE_API;
        case DOMAIN_STRUCT:
            return ((StructDomain *)d)->mode == API_MODE_API;
        case DOMAIN_TYPE:
            return ((TypeDomain *)d)->mode == TYPE_MODE_API_RENAME ||
                   ((TypeDomain *)d)->mode == TYPE_MODE_API_STRUCT;
        case DOMAIN_MACRO:
            return ((MacroDomain *)d)->mode == API_MODE_API;
        default:
            return 0;
    }
}

/* ================================================================== */
/* generate_docs - top-level documentation generator                  */
/* ================================================================== */

int generate_docs(Project *proj, const char *output_dir) {
    if (!proj) return -1;

    ensure_dir(output_dir);

    /* Generate project-level README */
    generate_project_readme(proj, output_dir);

    /* Generate docs for each module recursively */
    /* We walk the domain tree and generate docs for each module */
    return 0;
}

/* Called from generator after module dir is created */
void generate_module_docs(Domain *mod, const char *dir) {
    if (!mod || mod->type != DOMAIN_MODULE) return;

    generate_mod_readme(mod, dir);
    generate_mod_api(mod, dir);
    generate_mod_dev(mod, dir);
    generate_mod_doc(mod, dir);

    /* Recurse into child modules */
    for (int i = 0; i < mod->child_count; i++) {
        if (mod->children[i]->type == DOMAIN_MODULE) {
            char sub_dir[MAX_PATH_LEN];
            snprintf(sub_dir, sizeof(sub_dir), "%s/%s", dir, mod->children[i]->name);
            generate_module_docs(mod->children[i], sub_dir);
        }
    }
}

/* ================================================================== */
/* generate_project_readme - project-level README.md                  */
/* ================================================================== */

static void generate_project_readme(Project *proj, const char *output_dir) {
    char file_path[MAX_PATH_LEN];
    snprintf(file_path, sizeof(file_path), "%s/README.md", output_dir);

    FILE *f = fopen(file_path, "w");
    if (!f) return;

    fprintf(f, "# %s\n\n", proj->name);
    if (proj->root->comment) {
        fprintf(f, "%s\n\n", proj->root->comment);
    }

    fprintf(f, "## 文档\n\n");
    fprintf(f, "- [API 文档](API.md)\n");
    fprintf(f, "- [开发文档](DEV.md)\n");
    fprintf(f, "- [完整文档](DOC.md)\n\n");

    fprintf(f, "## 目录结构\n\n");
    fprintf(f, "```\n");
    fprintf(f, "%s/\n", proj->name);
    fprintf(f, "├── CMakeLists.txt\n");
    fprintf(f, "├── src/\n");
    fprintf(f, "│   ├── main.c\n");

    /* Module tree */
    for (int i = 0; i < proj->root->child_count; i++) {
        Domain *child = proj->root->children[i];
        if (child->type == DOMAIN_MODULE) {
            fprintf(f, "│   ├── %s/\n", child->name);
            fprintf(f, "│   │   ├── CMakeLists.txt\n");
            fprintf(f, "│   │   ├── %s.c\n", child->name);
            fprintf(f, "│   │   ├── %s.h\n", child->name);
            fprintf(f, "│   │   ├── README.md\n");
            fprintf(f, "│   │   ├── API.md\n");
            fprintf(f, "│   │   ├── DEV.md\n");
            fprintf(f, "│   │   ├── DOC.md\n");
            fprintf(f, "│   │   └── .cboot\n");
        }
    }
    fprintf(f, "│   └── docs/\n");
    fprintf(f, "└── lib/\n");
    fprintf(f, "```\n\n");

    fprintf(f, "*Generated by CBoot v%s*\n", CBOOT_VERSION);
    fclose(f);
}

/* ================================================================== */
/* generate_mod_readme - module README.md                             */
/* ================================================================== */

static void generate_mod_readme(Domain *mod, const char *dir) {
    char file_path[MAX_PATH_LEN];
    snprintf(file_path, sizeof(file_path), "%s/README.md", dir);

    FILE *f = fopen(file_path, "w");
    if (!f) return;

    fprintf(f, "# %s\n\n", mod->name);
    if (mod->comment) {
        fprintf(f, "%s\n\n", mod->comment);
    }

    fprintf(f, "## 文档\n\n");
    fprintf(f, "- [API 文档](API.md) - API 接口说明\n");
    fprintf(f, "- [开发文档](DEV.md) - 开发设计文档\n");
    fprintf(f, "- [完整文档](DOC.md) - 所有定义和注释\n\n");

    fprintf(f, "## 目录结构\n\n");
    fprintf(f, "```\n");
    fprintf(f, "%s/\n", mod->name);
    fprintf(f, "├── CMakeLists.txt\n");
    fprintf(f, "├── %s.c\n", mod->name);
    fprintf(f, "├── %s.h\n", mod->name);
    fprintf(f, "├── README.md\n");
    fprintf(f, "├── API.md\n");
    fprintf(f, "├── DEV.md\n");
    fprintf(f, "├── DOC.md\n");
    fprintf(f, "└── .cboot\n");

    /* Child modules */
    for (int i = 0; i < mod->child_count; i++) {
        if (mod->children[i]->type == DOMAIN_MODULE) {
            fprintf(f, "    └── %s/\n", mod->children[i]->name);
        }
    }
    fprintf(f, "```\n\n");

    fprintf(f, "*Generated by CBoot v%s*\n", CBOOT_VERSION);
    fclose(f);
}

/* ================================================================== */
/* generate_mod_api - module API.md                                   */
/* ================================================================== */

static void generate_mod_api(Domain *mod, const char *dir) {
    char file_path[MAX_PATH_LEN];
    snprintf(file_path, sizeof(file_path), "%s/API.md", dir);

    FILE *f = fopen(file_path, "w");
    if (!f) return;

    fprintf(f, "# %s API 文档\n\n", mod->name);

    /* API Functions */
    int has_api = 0;
    for (int i = 0; i < mod->child_count; i++) {
        Domain *child = mod->children[i];
        if (child->type == DOMAIN_FUNCTION && is_api(child)) {
            if (!has_api) {
                fprintf(f, "## API 函数\n\n");
                has_api = 1;
            }

            FunctionDomain *func = (FunctionDomain *)child;
            fprintf(f, "### %s %s()\n\n", func->return_type, child->name);

            if (child->comment) {
                fprintf(f, "**说明**: %s\n\n", child->comment);
            }
            if (func->value) {
                fprintf(f, "**业务逻辑**: %s\n\n", func->value);
            }

            /* Parameters */
            int has_params = 0;
            for (int j = 0; j < child->child_count; j++) {
                Domain *param = child->children[j];
                if (param->type == DOMAIN_MEMBER) {
                    MemberDomain *mb = (MemberDomain *)param;
                    if (!has_params) {
                        fprintf(f, "**参数**:\n\n");
                        fprintf(f, "| 名称 | 类型 | 说明 |\n");
                        fprintf(f, "|------|------|------|\n");
                        has_params = 1;
                    }
                    fprintf(f, "| `%s` | `%s` | %s |\n",
                            param->name, mb->type,
                            param->comment ? param->comment : "-");
                }
            }
            if (has_params) fprintf(f, "\n");
        }
    }

    /* API Types */
    int has_types = 0;
    for (int i = 0; i < mod->child_count; i++) {
        Domain *child = mod->children[i];
        if ((child->type == DOMAIN_STRUCT || child->type == DOMAIN_TYPE) && is_api(child)) {
            if (!has_types) {
                fprintf(f, "## API 类型\n\n");
                has_types = 1;
            }

            fprintf(f, "### %s\n\n", child->name);
            if (child->comment) {
                fprintf(f, "**说明**: %s\n\n", child->comment);
            }

            if (child->type == DOMAIN_TYPE) {
                TypeDomain *td = (TypeDomain *)child;
                if ((td->mode == TYPE_MODE_API_RENAME) && td->value) {
                    fprintf(f, "**底层类型**: `%s`\n\n", td->value);
                }
            }

            /* Members */
            if (child->child_count > 0) {
                fprintf(f, "**成员**:\n\n");
                fprintf(f, "| 名称 | 类型 | 说明 |\n");
                fprintf(f, "|------|------|------|\n");
                for (int j = 0; j < child->child_count; j++) {
                    Domain *mem = child->children[j];
                    if (mem->type == DOMAIN_MEMBER) {
                        MemberDomain *mb = (MemberDomain *)mem;
                        fprintf(f, "| `%s` | `%s` | %s |\n",
                                mem->name, mb->type,
                                mem->comment ? mem->comment : "-");
                    }
                }
                fprintf(f, "\n");
            }
        }
    }

    /* API Macros */
    int has_macros = 0;
    for (int i = 0; i < mod->child_count; i++) {
        Domain *child = mod->children[i];
        if (child->type == DOMAIN_MACRO && is_api(child)) {
            if (!has_macros) {
                fprintf(f, "## API 宏\n\n");
                fprintf(f, "| 名称 | 值 | 说明 |\n");
                fprintf(f, "|------|------|------|\n");
                has_macros = 1;
            }

            MacroDomain *md = (MacroDomain *)child;
            fprintf(f, "| `%s` | `%s` | %s |\n",
                    child->name,
                    md->value ? md->value : "-",
                    child->comment ? child->comment : "-");
        }
    }
    if (has_macros) fprintf(f, "\n");

    if (!has_api && !has_types && !has_macros) {
        fprintf(f, "此模块没有公开 API。\n\n");
    }

    fprintf(f, "*Generated by CBoot v%s*\n", CBOOT_VERSION);
    fclose(f);
}

/* ================================================================== */
/* generate_mod_dev - module DEV.md                                   */
/* ================================================================== */

static void write_dev_functions(Domain *mod, FILE *f) {
    int has_funcs = 0;
    for (int i = 0; i < mod->child_count; i++) {
        Domain *child = mod->children[i];
        if (child->type == DOMAIN_FUNCTION) {
            FunctionDomain *func = (FunctionDomain *)child;
            if (!has_funcs) {
                fprintf(f, "## 函数\n\n");
                has_funcs = 1;
            }

            fprintf(f, "### %s %s()\n\n", func->return_type, child->name);

            if (func->value) {
                fprintf(f, "**业务逻辑**: %s\n\n", func->value);
            }
            if (child->comment) {
                fprintf(f, "**说明**: %s\n\n", child->comment);
            }

            /* Parameters */
            for (int j = 0; j < child->child_count; j++) {
                Domain *param = child->children[j];
                if (param->type == DOMAIN_MEMBER) {
                    MemberDomain *mb = (MemberDomain *)param;
                    fprintf(f, "- **参数 `%s`** (`%s`)", param->name, mb->type);
                    if (param->comment) fprintf(f, ": %s", param->comment);
                    fprintf(f, "\n");
                }
            }

            /* Local variables */
            for (int j = 0; j < child->child_count; j++) {
                Domain *var = child->children[j];
                if (var->type == DOMAIN_VARIABLE) {
                    VariableDomain *v = (VariableDomain *)var;
                    fprintf(f, "- **局部变量 `%s`** (`%s`)", var->name, v->type);
                    if (var->comment) fprintf(f, ": %s", var->comment);
                    fprintf(f, "\n");
                }
            }

            fprintf(f, "\n");
        }
    }
}

static void write_dev_types(Domain *mod, FILE *f) {
    int has_types = 0;
    for (int i = 0; i < mod->child_count; i++) {
        Domain *child = mod->children[i];
        if (child->type == DOMAIN_STRUCT || child->type == DOMAIN_TYPE) {
            if (!has_types) {
                fprintf(f, "## 类型\n\n");
                has_types = 1;
            }

            fprintf(f, "### %s\n\n", child->name);
            if (child->comment) fprintf(f, "**说明**: %s\n\n", child->comment);

            for (int j = 0; j < child->child_count; j++) {
                Domain *mem = child->children[j];
                if (mem->type == DOMAIN_MEMBER) {
                    MemberDomain *mb = (MemberDomain *)mem;
                    fprintf(f, "- **`%s`** (`%s`)", mem->name, mb->type);
                    if (mem->comment) fprintf(f, ": %s", mem->comment);
                    fprintf(f, "\n");
                }
            }
            fprintf(f, "\n");
        }
    }
}

static void write_dev_macros(Domain *mod, FILE *f) {
    int has_macros = 0;
    for (int i = 0; i < mod->child_count; i++) {
        Domain *child = mod->children[i];
        if (child->type == DOMAIN_MACRO) {
            if (!has_macros) {
                fprintf(f, "## 宏\n\n");
                has_macros = 1;
            }

            MacroDomain *md = (MacroDomain *)child;
            fprintf(f, "- **`%s`**", child->name);
            if (md->value) fprintf(f, " = `%s`", md->value);
            if (child->comment) fprintf(f, ": %s", child->comment);
            fprintf(f, "\n");
        }
    }
    if (has_macros) fprintf(f, "\n");
}

static void generate_mod_dev(Domain *mod, const char *dir) {
    char file_path[MAX_PATH_LEN];
    snprintf(file_path, sizeof(file_path), "%s/DEV.md", dir);

    FILE *f = fopen(file_path, "w");
    if (!f) return;

    fprintf(f, "# %s 开发文档\n\n", mod->name);
    if (mod->comment) fprintf(f, "%s\n\n", mod->comment);

    write_dev_functions(mod, f);
    write_dev_types(mod, f);
    write_dev_macros(mod, f);

    /* Child module API links */
    int has_child_mods = 0;
    for (int i = 0; i < mod->child_count; i++) {
        if (mod->children[i]->type == DOMAIN_MODULE) {
            if (!has_child_mods) {
                fprintf(f, "## 子模块 API\n\n");
                has_child_mods = 1;
            }
            Domain *child = mod->children[i];
            fprintf(f, "- [%s](%s/API.md)", child->name, child->name);
            if (child->comment) fprintf(f, ": %s", child->comment);
            fprintf(f, "\n");
        }
    }
    if (has_child_mods) fprintf(f, "\n");

    fprintf(f, "*Generated by CBoot v%s*\n", CBOOT_VERSION);
    fclose(f);
}

/* ================================================================== */
/* generate_mod_doc - module DOC.md (完整文档 + TOC)                   */
/* ================================================================== */

static void write_doc_toc(Domain *mod, FILE *f) {
    fprintf(f, "## 目录\n\n");

    /* Functions */
    for (int i = 0; i < mod->child_count; i++) {
        Domain *child = mod->children[i];
        if (child->type == DOMAIN_FUNCTION) {
            fprintf(f, "- [%s()](#%s)\n", child->name, child->name);
        }
    }

    /* Types */
    for (int i = 0; i < mod->child_count; i++) {
        Domain *child = mod->children[i];
        if (child->type == DOMAIN_STRUCT || child->type == DOMAIN_TYPE) {
            fprintf(f, "- [%s](#%s)\n", child->name, child->name);
        }
    }

    /* Macros */
    for (int i = 0; i < mod->child_count; i++) {
        Domain *child = mod->children[i];
        if (child->type == DOMAIN_MACRO) {
            fprintf(f, "- [`%s`](#%s)\n", child->name, child->name);
        }
    }

    fprintf(f, "\n---\n\n");
}

static void write_doc_functions(Domain *mod, FILE *f) {
    for (int i = 0; i < mod->child_count; i++) {
        Domain *child = mod->children[i];
        if (child->type != DOMAIN_FUNCTION) continue;

        FunctionDomain *func = (FunctionDomain *)child;
        fprintf(f, "## %s()\n\n", child->name);

        fprintf(f, "**声明**: `%s %s(", func->return_type, child->name);
        int first = 1;
        for (int j = 0; j < child->child_count; j++) {
            Domain *param = child->children[j];
            if (param->type == DOMAIN_MEMBER) {
                MemberDomain *mb = (MemberDomain *)param;
                if (!first) fprintf(f, ", ");
                fprintf(f, "%s %s", mb->type, param->name);
                first = 0;
            }
        }
        fprintf(f, ")`\n\n");

        if (child->comment) fprintf(f, "**注释**: %s\n\n", child->comment);
        if (func->value) fprintf(f, "**业务逻辑**: %s\n\n", func->value);

        /* Parameters table */
        int has_params = 0;
        for (int j = 0; j < child->child_count; j++) {
            Domain *p = child->children[j];
            if (p->type == DOMAIN_MEMBER) {
                if (!has_params) {
                    fprintf(f, "| 参数 | 类型 | 说明 |\n");
                    fprintf(f, "|------|------|------|\n");
                    has_params = 1;
                }
                MemberDomain *mb = (MemberDomain *)p;
                fprintf(f, "| `%s` | `%s` | %s |\n",
                        p->name, mb->type, p->comment ? p->comment : "-");
            }
        }
        if (has_params) fprintf(f, "\n");

        /* Call stack */
        fprintf(f, "**调用栈**: (此函数在模块 %s 中定义)\n\n", mod->name);

        /* Code */
        if (func->code) {
            fprintf(f, "```c\n%s\n```\n\n", func->code);
        }

        fprintf(f, "---\n\n");
    }
}

static void write_doc_definitions(Domain *mod, FILE *f) {
    int has_any = 0;

    for (int i = 0; i < mod->child_count; i++) {
        Domain *child = mod->children[i];
        if (child->type == DOMAIN_STRUCT) {
            if (!has_any) {
                fprintf(f, "## 定义\n\n");
                has_any = 1;
            }
            fprintf(f, "### struct %s\n\n", child->name);
            if (child->comment) fprintf(f, "**注释**: %s\n\n", child->comment);
            fprintf(f, "```c\n");
            fprintf(f, "typedef struct %s {\n", child->name);
            for (int j = 0; j < child->child_count; j++) {
                Domain *mem = child->children[j];
                if (mem->type == DOMAIN_MEMBER) {
                    MemberDomain *mb = (MemberDomain *)mem;
                    fprintf(f, "    %s %s;\n", mb->type, mem->name);
                }
            }
            fprintf(f, "} %s;\n", child->name);
            fprintf(f, "```\n\n");
        } else if (child->type == DOMAIN_TYPE) {
            if (!has_any) {
                fprintf(f, "## 定义\n\n");
                has_any = 1;
            }
            TypeDomain *td = (TypeDomain *)child;
            fprintf(f, "### typedef %s\n\n", child->name);
            if (child->comment) fprintf(f, "**注释**: %s\n\n", child->comment);
            if (td->mode == TYPE_MODE_RENAME || td->mode == TYPE_MODE_API_RENAME) {
                fprintf(f, "```c\ntypedef %s %s;\n```\n\n",
                        td->value ? td->value : "int", child->name);
            } else {
                fprintf(f, "```c\ntypedef struct %s { ... } %s;\n```\n\n",
                        child->name, child->name);
            }
        } else if (child->type == DOMAIN_MACRO) {
            if (!has_any) {
                fprintf(f, "## 定义\n\n");
                has_any = 1;
            }
            MacroDomain *md = (MacroDomain *)child;
            fprintf(f, "### `%s`\n\n", child->name);
            if (child->comment) fprintf(f, "**注释**: %s\n\n", child->comment);
            fprintf(f, "```c\n#define %s", child->name);
            if (md->value) fprintf(f, " %s", md->value);
            fprintf(f, "\n```\n\n");
        }
    }
}

static void generate_mod_doc(Domain *mod, const char *dir) {
    char file_path[MAX_PATH_LEN];
    snprintf(file_path, sizeof(file_path), "%s/DOC.md", dir);

    FILE *f = fopen(file_path, "w");
    if (!f) return;

    fprintf(f, "# %s 完整文档\n\n", mod->name);
    if (mod->comment) fprintf(f, "%s\n\n", mod->comment);

    write_doc_toc(mod, f);
    write_doc_functions(mod, f);
    write_doc_definitions(mod, f);

    fprintf(f, "*Generated by CBoot v%s*\n", CBOOT_VERSION);
    fclose(f);
}